
from typing import Any, Optional
# ─────────────────────────────────────────────────────────────
#  DB layout definition
#  Each entry: (name, type, byte_offset, bit_index_or_None)
# ─────────────────────────────────────────────────────────────

DB_LAYOUT: list[tuple[str, str, int, Any]] = [
    # ── Booleans  byte 0 ──────────────────────────────────────
    ("START",               "BOOL",   0,    0),
    ("STOP",                "BOOL",   0,    1),
    ("T0_Start_Heat",       "BOOL",   0,    2),
    ("T0_StopHeat",         "BOOL",   0,    3),
    ("P1_Start_Heat",       "BOOL",   0,    4),
    ("P1_Start_Pressure",   "BOOL",   0,    5),
    ("P1_Start_Oil",        "BOOL",   0,    6),
    ("P1_BitCountTimes",    "BOOL",   0,    7),
    # ── Booleans  byte 1 ──────────────────────────────────────
    ("P2_Start_Heat",       "BOOL",   1,    0),
    ("P2_Start_Pressure",   "BOOL",   1,    1),
    ("P2_Start_Oil",        "BOOL",   1,    2),
    ("P2_BitCountTimes",    "BOOL",   1,    3),
    ("P3_Start_Heat",       "BOOL",   1,    4),
    ("P3_Start_Pressure",   "BOOL",   1,    5),
    ("P3_Start_Oil",        "BOOL",   1,    6),
    ("P3_BitCountTimes",    "BOOL",   1,    7),
    # ── T0 Reals ──────────────────────────────────────────────
    ("T0_TemperatureSetting", "REAL",  2,   None),
    ("T0_TempLimitHIGH",      "REAL",  6,   None),
    ("T0_TempLimitLOW",       "REAL",  10,  None),
    ("T0_TempOffset",         "REAL",  14,  None),
    # ── P1 Settings ───────────────────────────────────────────
    ("P1_TemperatureSetting", "REAL",  18,  None),
    ("P1_TempLimitHIGH",      "REAL",  22,  None),
    ("P1_TempLimitLOW",       "REAL",  26,  None),
    ("P1_Temp1Offset",        "REAL",  30,  None),
    ("P1_Temp2Offset",        "REAL",  34,  None),
    ("P1_Temp3Offset",        "REAL",  38,  None),
    ("P1_PressureSetting",    "REAL",  42,  None),
    ("P1_PressureHoseOffset", "REAL",  46,  None),
    ("P1_PressureITVOffset",  "REAL",  50,  None),
    ("P1_Air_FillingTime",    "DINT",  54,  None),
    ("P1_Air_HoldingTime",    "DINT",  58,  None),
    ("P1_Air_ReleaseTime",    "DINT",  62,  None),
    ("P1_Oil_Start_Time",     "DINT",  66,  None),
    ("P1_Oil_End_Time",       "DINT",  70,  None),
    ("P1_CountTimes",         "INT",   74,  None),
    # ── P2 Settings ───────────────────────────────────────────
    ("P2_TemperatureSetting", "REAL",  76,  None),
    ("P2_TempLimitHIGH",      "REAL",  80,  None),
    ("P2_TempLimitLOW",       "REAL",  84,  None),
    ("P2_Temp1Offset",        "REAL",  88,  None),
    ("P2_Temp2Offset",        "REAL",  92,  None),
    ("P2_Temp3Offset",        "REAL",  96,  None),
    ("P2_PressureSetting",    "REAL",  100, None),
    ("P2_PressureHoseOffset", "REAL",  104, None),
    ("P2_PressureITVOffset",  "REAL",  108, None),
    ("P2_Air_FillingTime",    "DINT",  112, None),
    ("P2_Air_HoldingTime",    "DINT",  116, None),
    ("P2_Air_ReleaseTime",    "DINT",  120, None),
    ("P2_Oil_Start_Time",     "DINT",  124, None),
    ("P2_Oil_End_Time",       "DINT",  128, None),
    ("P2_CountTimes",         "INT",   132, None),
    # ── P3 Settings ───────────────────────────────────────────
    ("P3_TemperatureSetting", "REAL",  134, None),
    ("P3_TempLimitHIGH",      "REAL",  138, None),
    ("P3_TempLimitLOW",       "REAL",  142, None),
    ("P3_Temp1Offset",        "REAL",  146, None),
    ("P3_Temp2Offset",        "REAL",  150, None),
    ("P3_Temp3Offset",        "REAL",  154, None),
    ("P3_PressureSetting",    "REAL",  158, None),
    ("P3_PressureHoseOffset", "REAL",  162, None),
    ("P3_PressureITVOffset",  "REAL",  166, None),
    ("P3_Air_FillingTime",    "DINT",  170, None),
    ("P3_Air_HoldingTime",    "DINT",  174, None),
    ("P3_Air_ReleaseTime",    "DINT",  178, None),
    ("P3_Oil_Start_Time",     "DINT",  182, None),
    ("P3_Oil_End_Time",       "DINT",  186, None),
    ("P3_CountTimes",         "INT",   190, None),
    # ── Alarm flag + T0 current ───────────────────────────────
    ("Bit_Alarm",             "BOOL",  192, 0),
    ("T0_Current_Temp",       "REAL",  194, None),
    # ── P1 Actuals ────────────────────────────────────────────
    ("P1_Current_Temp1",          "REAL",  198, None),
    ("P1_Current_Temp2",          "REAL",  202, None),
    ("P1_Current_Temp3",          "REAL",  206, None),
    ("P1_Current_PressureHose",   "REAL",  210, None),
    ("P1_Current_PressureITV",    "REAL",  214, None),
    ("P1_Air_FillingTime_Act",    "DINT",  218, None),
    ("P1_Air_HoldingTime_Act",    "DINT",  222, None),
    ("P1_Air_ReleaseTime_Act",    "DINT",  226, None),
    ("P1_Oil_Start_Time_Act",     "DINT",  230, None),
    ("P1_Oil_End_Time_Act",       "DINT",  234, None),
    ("P1_Number_Test_Times",      "INT",   238, None),
    # ── P2 Actuals ────────────────────────────────────────────
    ("P2_Current_Temp1",          "REAL",  240, None),
    ("P2_Current_Temp2",          "REAL",  244, None),
    ("P2_Current_Temp3",          "REAL",  248, None),
    ("P2_Current_PressureHose",   "REAL",  252, None),
    ("P2_Current_PressureITV",    "REAL",  256, None),
    ("P2_Air_FillingTime_Act",    "DINT",  260, None),
    ("P2_Air_HoldingTime_Act",    "DINT",  264, None),
    ("P2_Air_ReleaseTime_Act",    "DINT",  268, None),
    ("P2_Oil_Start_Time_Act",     "DINT",  272, None),
    ("P2_Oil_End_Time_Act",       "DINT",  276, None),
    ("P2_Number_Test_Times",      "INT",   280, None),
    # ── P3 Actuals ────────────────────────────────────────────
    ("P3_Current_Temp1",          "REAL",  282, None),
    ("P3_Current_Temp2",          "REAL",  286, None),
    ("P3_Current_Temp3",          "REAL",  290, None),
    ("P3_Current_PressureHose",   "REAL",  294, None),
    ("P3_Current_PressureITV",    "REAL",  298, None),
    ("P3_Air_FillingTime_Act",    "DINT",  302, None),
    ("P3_Air_HoldingTime_Act",    "DINT",  306, None),
    ("P3_Air_ReleaseTime_Act",    "DINT",  310, None),
    ("P3_Oil_Start_Time_Act",     "DINT",  314, None),
    ("P3_Oil_End_Time_Act",       "DINT",  318, None),
    ("P3_Number_Test_Times",      "INT",   322, None),
    # ── Alarm string ──────────────────────────────────────────
    ("Alarm_Info",                "STRING", 324, None),
]

# Total bytes to read: String at 324 + 2-byte header + 254 max chars = 580
DB_TOTAL_BYTES = 584
