from dataclasses import dataclass

@dataclass
class DBField:
    offset: int
    size: int
    data_type: str  # 'REAL', 'DINT', 'INT', 'BOOL', 'STRING'

DB_MAP = {
    # Bit Input
    "START":                  DBField(0,   1, "BOOL"),
    "STOP":                   DBField(0,   1, "BOOL"),
    "T0_StartHeat":           DBField(0,   1, "BOOL"),
    "T0_StopHeat":            DBField(0,   1, "BOOL"),
    "P1_StartHeat":           DBField(0,   1, "BOOL"),
    "P1_StartPressure":       DBField(0,   1, "BOOL"),
    "P1_StartOil":            DBField(0,   1, "BOOL"),
    "P1_BitCountTimes":       DBField(0,   1, "BOOL"),
    "P2_StartHeat":           DBField(1,   1, "BOOL"),
    "P2_StartPressure":       DBField(1,   1, "BOOL"),
    "P2_StartOil":            DBField(1,   1, "BOOL"),
    "P2_BitCountTimes":       DBField(1,   1, "BOOL"),
    "P3_StartHeat":           DBField(1,   1, "BOOL"),
    "P3_StartPressure":       DBField(1,   1, "BOOL"),
    "P3_StartOil":            DBField(1,   1, "BOOL"),
    "P3_BitCountTimes":       DBField(1,   1, "BOOL"),

    # Input - T0
    "T0_TemperatureSetting":  DBField(2,   4, "REAL"),
    "T0_TempLimitHIGH":       DBField(6,   4, "REAL"),
    "T0_TempLimitLOW":        DBField(10,  4, "REAL"),
    "T0_TempOffset":          DBField(14,  4, "REAL"),

    # Input - P1
    "P1_TemperatureSetting":  DBField(18,  4, "REAL"),
    "P1_TempLimitHIGH":       DBField(22,  4, "REAL"),
    "P1_TempLimitLOW":        DBField(26,  4, "REAL"),
    "P1_Temp1Offset":         DBField(30,  4, "REAL"),
    "P1_Temp2Offset":         DBField(34,  4, "REAL"),
    "P1_Temp3Offset":         DBField(38,  4, "REAL"),
    "P1_PressureSetting":     DBField(42,  4, "REAL"),
    "P1_PressureHoseOffset":  DBField(46,  4, "REAL"),
    "P1_PressureITVOffset":   DBField(50,  4, "REAL"),
    "P1_AirFillingTime":      DBField(54,  4, "DINT"),
    "P1_AirHoldingTime":      DBField(58,  4, "DINT"),
    "P1_AirReleaseTime":      DBField(62,  4, "DINT"),
    "P1_OilStartTime":        DBField(66,  4, "DINT"),
    "P1_OilEndTime":          DBField(70,  4, "DINT"),
    "P1_CountTimes":          DBField(74,  2, "INT"),

    # Input - P2
    "P2_TemperatureSetting":  DBField(76,  4, "REAL"),
    "P2_TempLimitHIGH":       DBField(80,  4, "REAL"),
    "P2_TempLimitLOW":        DBField(84,  4, "REAL"),
    "P2_Temp1Offset":         DBField(88,  4, "REAL"),
    "P2_Temp2Offset":         DBField(92,  4, "REAL"),
    "P2_Temp3Offset":         DBField(96,  4, "REAL"),
    "P2_PressureSetting":     DBField(100, 4, "REAL"),
    "P2_PressureHoseOffset":  DBField(104, 4, "REAL"),
    "P2_PressureITVOffset":   DBField(108, 4, "REAL"),
    "P2_AirFillingTime":      DBField(112, 4, "DINT"),
    "P2_AirHoldingTime":      DBField(116, 4, "DINT"),
    "P2_AirReleaseTime":      DBField(120, 4, "DINT"),
    "P2_OilStartTime":        DBField(124, 4, "DINT"),
    "P2_OilEndTime":          DBField(128, 4, "DINT"),
    "P2_CountTimes":          DBField(132, 2, "INT"),

    # Input - P3
    "P3_TemperatureSetting":  DBField(134, 4, "REAL"),
    "P3_TempLimitHIGH":       DBField(138, 4, "REAL"),
    "P3_TempLimitLOW":        DBField(142, 4, "REAL"),
    "P3_Temp1Offset":         DBField(146, 4, "REAL"),
    "P3_Temp2Offset":         DBField(150, 4, "REAL"),
    "P3_Temp3Offset":         DBField(154, 4, "REAL"),
    "P3_PressureSetting":     DBField(158, 4, "REAL"),
    "P3_PressureHoseOffset":  DBField(162, 4, "REAL"),
    "P3_PressureITVOffset":   DBField(166, 4, "REAL"),
    "P3_AirFillingTime":      DBField(170, 4, "DINT"),
    "P3_AirHoldingTime":      DBField(174, 4, "DINT"),
    "P3_AirReleaseTime":      DBField(178, 4, "DINT"),
    "P3_OilStartTime":        DBField(182, 4, "DINT"),
    "P3_OilEndTime":          DBField(186, 4, "DINT"),
    "P3_CountTimes":          DBField(190, 2, "INT"),

    # Bit Output
    "Bit_Alarm":              DBField(192, 1, "BOOL"),

    # Output
    "T0_CurrentTemp":         DBField(194, 4, "REAL"),
    "P1_CurrentTemp1":        DBField(198, 4, "REAL"),
    "P1_CurrentTemp2":        DBField(202, 4, "REAL"),
    "P1_CurrentTemp3":        DBField(206, 4, "REAL"),
    "P1_CurrentPressureHose": DBField(210, 4, "REAL"),
    "P1_CurrentPressureITV":  DBField(214, 4, "REAL"),
    "P1_AirFillingTime_Out":  DBField(218, 4, "DINT"),
    "P1_AirHoldingTime_Out":  DBField(222, 4, "DINT"),
    "P1_AirReleaseTime_Out":  DBField(226, 4, "DINT"),
    "P1_OilStartTime_Out":    DBField(230, 4, "DINT"),
    "P1_OilEndTime_Out":      DBField(234, 4, "DINT"),
    "P1_NumberTestTimes":     DBField(238, 2, "INT"),
    "P2_CurrentTemp1":        DBField(240, 4, "REAL"),
    "P2_CurrentTemp2":        DBField(244, 4, "REAL"),
    "P2_CurrentTemp3":        DBField(248, 4, "REAL"),
    "P2_CurrentPressureHose": DBField(252, 4, "REAL"),
    "P2_CurrentPressureITV":  DBField(256, 4, "REAL"),
    "P2_AirFillingTime_Out":  DBField(260, 4, "DINT"),
    "P2_AirHoldingTime_Out":  DBField(264, 4, "DINT"),
    "P2_AirReleaseTime_Out":  DBField(268, 4, "DINT"),
    "P2_OilStartTime_Out":    DBField(272, 4, "DINT"),
    "P2_OilEndTime_Out":      DBField(276, 4, "DINT"),
    "P2_NumberTestTimes":     DBField(280, 2, "INT"),
    "P3_CurrentTemp1":        DBField(282, 4, "REAL"),
    "P3_CurrentTemp2":        DBField(286, 4, "REAL"),
    "P3_CurrentTemp3":        DBField(290, 4, "REAL"),
    "P3_CurrentPressureHose": DBField(294, 4, "REAL"),
    "P3_CurrentPressureITV":  DBField(298, 4, "REAL"),
    "P3_AirFillingTime_Out":  DBField(302, 4, "DINT"),
    "P3_AirHoldingTime_Out":  DBField(306, 4, "DINT"),
    "P3_AirReleaseTime_Out":  DBField(310, 4, "DINT"),
    "P3_OilStartTime_Out":    DBField(314, 4, "DINT"),
    "P3_OilEndTime_Out":      DBField(318, 4, "DINT"),
    "P3_NumberTestTimes":     DBField(322, 2, "INT"),
    "Alarm_Info":             DBField(324, 256, "STRING"),
}

BOOL_BIT_INDEX = {
    "START":            (0, 0), "STOP":             (0, 1),
    "T0_StartHeat":     (0, 2), "T0_StopHeat":      (0, 3),
    "P1_StartHeat":     (0, 4), "P1_StartPressure": (0, 5),
    "P1_StartOil":      (0, 6), "P1_BitCountTimes": (0, 7),
    "P2_StartHeat":     (1, 0), "P2_StartPressure": (1, 1),
    "P2_StartOil":      (1, 2), "P2_BitCountTimes": (1, 3),
    "P3_StartHeat":     (1, 4), "P3_StartPressure": (1, 5),
    "P3_StartOil":      (1, 6), "P3_BitCountTimes": (1, 7),
    "Bit_Alarm":        (192, 0),
}

WRITABLE_FIELDS = {
    "T0_TemperatureSetting", "T0_TempLimitHIGH", "T0_TempLimitLOW", "T0_TempOffset",
    "P1_TemperatureSetting", "P1_TempLimitHIGH", "P1_TempLimitLOW",
    "P1_Temp1Offset", "P1_Temp2Offset", "P1_Temp3Offset",
    "P1_PressureSetting", "P1_PressureHoseOffset", "P1_PressureITVOffset",
    "P1_AirFillingTime", "P1_AirHoldingTime", "P1_AirReleaseTime",
    "P1_OilStartTime", "P1_OilEndTime", "P1_CountTimes",
    "P2_TemperatureSetting", "P2_TempLimitHIGH", "P2_TempLimitLOW",
    "P2_Temp1Offset", "P2_Temp2Offset", "P2_Temp3Offset",
    "P2_PressureSetting", "P2_PressureHoseOffset", "P2_PressureITVOffset",
    "P2_AirFillingTime", "P2_AirHoldingTime", "P2_AirReleaseTime",
    "P2_OilStartTime", "P2_OilEndTime", "P2_CountTimes",
    "P3_TemperatureSetting", "P3_TempLimitHIGH", "P3_TempLimitLOW",
    "P3_Temp1Offset", "P3_Temp2Offset", "P3_Temp3Offset",
    "P3_PressureSetting", "P3_PressureHoseOffset", "P3_PressureITVOffset",
    "P3_AirFillingTime", "P3_AirHoldingTime", "P3_AirReleaseTime",
    "P3_OilStartTime", "P3_OilEndTime", "P3_CountTimes",
    # Bit inputs (lệnh điều khiển)
    "START", "STOP",
    "T0_StartHeat", "T0_StopHeat",
    "P1_StartHeat", "P1_StartPressure", "P1_StartOil", "P1_BitCountTimes",
    "P2_StartHeat", "P2_StartPressure", "P2_StartOil", "P2_BitCountTimes",
    "P3_StartHeat", "P3_StartPressure", "P3_StartOil", "P3_BitCountTimes",
}